[colors.primary]
background = '#00141D'
foreground = '#c9e1ec'

[colors.cursor]
text = '#c9e1ec'
cursor = '#c9e1ec'

[colors.normal]
black = '#00141D'
red = '#279BCF'
green = '#29B6F6'
yellow = '#48B2E2'
blue = '#4FC3F7'
magenta = '#6ECEF9'
cyan = '#89B4C8'
white = '#c9e1ec'

[colors.bright]
black = '#8c9da5'
red = '#279BCF'
green = '#29B6F6'
yellow = '#48B2E2'
blue = '#4FC3F7'
magenta = '#6ECEF9'
cyan = '#89B4C8'
white = '#c9e1ec'
