--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/bran/Pictures/Wallpapers/cat-sound.png"

-- Special
background="#12121b"
foreground="#e6d2f1"
cursor="#e6d2f1"

-- Colors
color0="#12121b"
color1="#F8BD96"
color2="#F18EAC"
color3="#9FD7A7"
color4="#ABE9B3"
color5="#9AB0D2"
color6="#DDB6F2"
color7="#e6d2f1"
color8="#a193a8"
color9="#F8BD96"
color10="#F18EAC"
color11="#9FD7A7"
color12="#ABE9B3"
color13="#9AB0D2"
color14="#DDB6F2"
color15="#e6d2f1"
