# Shell variables
# Generated by 'wal'
wallpaper='/home/bran/Pictures/Wallpapers/material-tux.png'

# Special
background='#00141D'
foreground='#c9e1ec'
cursor='#c9e1ec'

# Colors
color0='#00141D'
color1='#279BCF'
color2='#29B6F6'
color3='#48B2E2'
color4='#4FC3F7'
color5='#6ECEF9'
color6='#89B4C8'
color7='#c9e1ec'
color8='#8c9da5'
color9='#279BCF'
color10='#29B6F6'
color11='#48B2E2'
color12='#4FC3F7'
color13='#6ECEF9'
color14='#89B4C8'
color15='#c9e1ec'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
