# Shell variables
# Generated by 'wal'
wallpaper='/home/bran/Pictures/Wallpapers/cat-sound.png'

# Special
background='#12121b'
foreground='#e6d2f1'
cursor='#e6d2f1'

# Colors
color0='#12121b'
color1='#F8BD96'
color2='#F18EAC'
color3='#9FD7A7'
color4='#ABE9B3'
color5='#9AB0D2'
color6='#DDB6F2'
color7='#e6d2f1'
color8='#a193a8'
color9='#F8BD96'
color10='#F18EAC'
color11='#9FD7A7'
color12='#ABE9B3'
color13='#9AB0D2'
color14='#DDB6F2'
color15='#e6d2f1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
