--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/bran/Pictures/Wallpapers/material-tux.png"

-- Special
background="#00141D"
foreground="#c9e1ec"
cursor="#c9e1ec"

-- Colors
color0="#00141D"
color1="#279BCF"
color2="#29B6F6"
color3="#48B2E2"
color4="#4FC3F7"
color5="#6ECEF9"
color6="#89B4C8"
color7="#c9e1ec"
color8="#8c9da5"
color9="#279BCF"
color10="#29B6F6"
color11="#48B2E2"
color12="#4FC3F7"
color13="#6ECEF9"
color14="#89B4C8"
color15="#c9e1ec"
